[book]
title = "API Scanner"
description = "User manual for API Scanner"
authors = ["CySecurity"]
language = "en"

[output.html]
site-url = "/api-scanner-docker/"
default-theme = "light"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/CSPF-Founder/api-scanner-docker"
